import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import useSpeechmaticsRt from '@/useSpeechmaticsRt'

export default function Home() {

  const {
    isConnected,
    sessionEnd,
    sessionStart,
    partialTranscript,
    transcript,
  } = useSpeechmaticsRt({ jwt: smJwt });


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        {isConnected ? <div>Connected</div> : <div>Not Connected</div>}
        <button onClick={() => sessionStart?.()}>Start</button>
        <button onClick={() => sessionEnd?.()}>Stop</button>
        <div className="card">{transcript}</div>
        <div className="card">{partialTranscript}</div>
      </main>
    </>
  )
}


const smJwt =
  "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzbWlzc3VlciIsImV4cCI6MTY4MzIyNjcyNCwibmJmIjoxNjgzMjE5NTI0LCJpYXQiOjE2ODMyMjMxMjQsImNvbnRyYWN0X2lkIjoiMTUiLCJwcm9kdWN0IjoicnQiLCJ1c2VyX2lkIjoic2VsZnNlcnZpY2UtMTQiLCJjb25uZWN0aW9uX3F1b3RhIjoiMiJ9.Yh6dp7qxLs__UGHXU-W0UPUeW1BLiLmm_c0CALX3CfNLzvDuGpxzvPVtaAPX7qDIYe1-rMzkg3QodDv2vEFyWNL_p7mgi2-kFfHY17A3DcoabuhKyt6hdYAo3b0AKnY52BBsbi-08T8BX140kMkZApo7xvqGMmIX-kalL-iq31HHTs313p6HVTHJZuvCu9sambh9w9tGIkOxv_tlBVy5NLyncC1PHhEdPfjbrRyG48404g_h0oR0Fo2fXw9rnmziU5cdl3rh5US-YhAl2geYB44eXvrXpJp5A7r-BVWIKoCUT0maBwmtaENN55f8YYtvYUNg5DMvGkWKKvpZ-pHuNy-Qnpm7uIfayLNGifqYR2FPMnV9PNHJNYCWn6fKWUjGOAh3sqpHEGz44bl2TObKwN8H7kfLISRs3Hg8AfO-81LPUzK1szVYd8aj1ku7I8-eAZAptXoo6qBD_COxj6StvxZ9ne4ZTZFVwXyMUjPFvRFvt4DDThPLXaUFduu6DV3_";