import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import useSpeechmaticsRt from '@/useSpeechmaticsRt'

export default function Home() {

  const {
    isConnected,
    sessionEnd,
    sessionStart,
    partialTranscript,
    transcript,
  } = useSpeechmaticsRt({ jwt: smJwt });


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        {isConnected ? <div>Connected</div> : <div>Not Connected</div>}
        <button onClick={() => sessionStart?.()}>Start</button>
        <button onClick={() => sessionEnd?.()}>Stop</button>
        <div className="card">{transcript}</div>
        <div className="card">{partialTranscript}</div>
      </main>
    </>
  )
}


const smJwt =
  "GENERATED_JWT";
